- name: "Get all devices with no FS"
  shell: lsblk -o NAME,FSTYPE -dsn  | awk '$2 == "" {print $1}'
  register: devices

- debug:
    var: devices.stdout_lines

- name: "Get ScaleIO token for Auth"
  uri:
    url: https://{{ vxflex_gateway_ip }}:{{ vxflex_gateway_https_port }}/api/login
    return_content: yes
    user: "{{ vxflex_gateway_username }}"
    password: "{{ vxflex_gateway_pw }}"
    force_basic_auth: yes
    validate_certs: False
    status_code:
      - 200
      - 201
      - 202
  register: msg

- name: "Query SDS ID Number to Pass to Create Device"
  uri:
    url: https://{{ vxflex_gateway_ip }}:{{ vxflex_gateway_https_port }}/api/types/Sds/instances/action/queryIdByKey
    method: POST
    user: "{{ vxflex_gateway_username }}"
    password: "{{ msg.json }}"
    body: { "name": "{{ ansible_facts['nodename'] }}"}
    force_basic_auth: yes
    body_format: json
    validate_certs: False
    status_code:
      - 200
      - 201
      - 202
  register: sds_id_number


- name: "Query Protection ID to pass to Create Device"
  uri:
    url: https://{{ vxflex_gateway_ip }}:{{ vxflex_gateway_https_port }}/api/types/ProtectionDomain/instances/action/queryIdByKey
    method: POST
    user: "{{ vxflex_gateway_username }}"
    password: "{{ msg.json }}"
    body: { "name": "{{ vxflex_protection_domain_name }}"}
    force_basic_auth: yes
    body_format: json
    validate_certs: False
    status_code:
      - 200
      - 201
      - 202
  register: protection_domain_id

- name: "Query Storage Pool ID to pass to Create Device"
  uri:
    url: https://{{ vxflex_gateway_ip }}:{{ vxflex_gateway_https_port }}/api/types/StoragePool/instances/action/queryIdByKey
    method: POST
    user: "{{ vxflex_gateway_username }}"
    password: "{{ msg.json }}"
    body: { "name": "{{ vxflex_storage_pool_name }}", "protectionDomainId": "{{ protection_domain_id.json }}"}
    force_basic_auth: yes
    body_format: json
    validate_certs: False
    status_code:
      - 200
      - 201
      - 202
  register: storage_pool_id

- name: "Storage Pool ID"
  debug:
    var: storage_pool_id.json

- name: "Add device to SDS servers"
  uri:
    url: https://{{ vxflex_gateway_ip }}:{{ vxflex_gateway_https_port }}/api/types/Device/instances
    method: POST
    user: "{{ vxflex_gateway_username }}"
    password: "{{ msg.json }}"
    body: {"sdsId":"{{ sds_id_number.json }}", "deviceCurrentPathname": "/dev/{{ item }}", "storagePoolId": "{{ storage_pool_id.json }}", "testMode": "noTest", "forceDeviceTakeover": "TRUE"}
    force_basic_auth: yes
    body_format: json
    validate_certs: False
    status_code:
      - 200
      - 201
      - 202
      - 500
  with_items: "{{ devices.stdout_lines }}"
